name: Docker Image CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dockerfile
        uses: actions/checkout@v2
      # 使用Docker官方制作的action
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and Push Docker Iamge
        uses: docker/build-push-action@v1
        with: 
          registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
          username: ${{ secrets.ALI_DOCKER_HUB_USN }}
          password: ${{ secrets.ALI_DOCKER_HUB_PWD }}
          repository: chasenzh/chasenzh-repository
          tag_with_sha: true

      # 使用Aliyun操作指南提供的命令
      # - name: Build Docker image
      #   run: |
      #     docker build -t locale:tag .
          
      # - name: Push to Ali Docker Repository
      #   run: |
      #     docker login -u ${{ secrets.ALI_DOCKER_HUB_USN }} -p ${{ secrets.ALI_DOCKER_HUB_PWD }} ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
      #     docker tag locale ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/chasenzh/chasenzh-repository:tag
      #     docker push ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/chasenzh/chasenzh-repository:tag
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALI_SERVER }}
          username: ${{ secrets.ALI_USERNAME }}
          password: ${{ secrets.ALI_DOCKER_HUB_PWD }}
          port: ${{ secrets.ALI_SERVER_PORT }}
          script: |
            if [[ -n $(docker ps -q -f "name=^blog-page$") ]];then
              docker stop blog-page
              docker rm blog-page
              docker rmi blog-page
            else
              echo "blog-page don't exist"
            fi
            docker login -u ${{ secrets.ALI_DOCKER_HUB_USN }} -p ${{ secrets.ALI_DOCKER_HUB_PWD }} ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
            
            docker pull ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/chasenzh/chasenzh-repository
            docker run -d -p 80:80 --name=blog-page ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/chasenzh/chasenzh-repository